### PR TITLE
fix: data race in Any

### PR DESCRIPTION
**Pull request by stevenh**
Close a data race possible in Any due to the use of values after the function exits.

### CODE REVIEW

**Comment by jussi-kalliokoski** [comment]
Thanks for the PR @stevenh! 🌟 

However, it seems that I'm missing something - could you describe in what scenario the data race will occur? In the current implementation, every partition writes to the results channel once when they complete, so N times for N partitions, and the coordinator collects N results from the channel, making sure that all partitions have completed, i.e. there's only an early return within a partition. I'm not sure I understand in what case a partition goroutine would be left running?

This means that the performance characteristics of the current implementation could be described as "rarely useful", use cases being such as data validation, where you expect the predicate to return the same result for each value.

Moreover, the proposed implementation has a few issues of its own:
- There's a race condition that could cause a panic upon [attempting to close the channel](https://github.com/jussi-kalliokoski/par/pull/2/files#diff-9f4ddb06889ca5df7db2896a8e49b609b47d7dd0e7b8ecc59d5d672cac0946b7R212). AFAIK go has no way to guarantee that the channel has not been closed already. You can get close by `select`ing on it right before, but there's still a window between the `select` and `close` in which another goroutine can close the channel. In our case, the window is even longer because we call the `predicate` in between, and that's expected to be potentially computation-heavy. In a synchronization sequence such as the proposed implementation, `context.Context` would be the preferred synchronization primitive as you can `cancel` the context multiple times without issues.
- As mentioned, due to the performance characteristics, the current implementation could be described as "rarely useful", however adding synchronization on each loop revolution brings `Any`, `All`, and `None` down to the level of "always slower than doing it in a single thread".

**Comment by stevenh** [comment]
The race occurs because of the short circuit evaluation in:
```go
	for p := 0; p < partitions; p++ {
		found = found || <-results
	}
```
This means that not all goroutines have exited when `Any` returns and as such the call could write to the passed in slice or data captured in the predicate function, as in the case of your tests. If you run `go test -race` you'll see the issue.

With regards to your second point, which I believe refers to the sync on read from `done` this could well slow things down but does it reduce it that much, as you still gain the parallel processing of predicate and the early exit on first result found? Maybe a benchmark to validate the behaviour?

Unfortunately due to the possibility of a data race it needs to ensure all goroutines have exited and without an early exit there is no gain at all.

**Comment by stevenh** [comment]
> In a synchronization sequence such as the proposed implementation, context.Context would be the preferred synchronization primitive as you can cancel the context multiple times without issues.

The use of the `done` channel could be replaced with a `context.Context` as mentioned but I believe in this use case it's actually heavier than a the current implementation as it uses a channel underneath with a lazy created channel that requires both an atomic and a lock interaction.

**Comment by jussi-kalliokoski** [comment]
> The race occurs because of the short circuit evaluation in:

Oh, that's true! :facepalm: Really nice catch! But I think the correct fix for the issue is to pull the channel read out of the conditional so that it's always evaluated, like so:

```go
	for p := 0; p < partitions; p++ {
		next := <-results
		found = found || next
	}
```

That way it just fixes the mismatch between how it was intended to work and how it was implemented without introducing additional synchronization. WDYT?

**Comment by stevenh** [comment]
> Oh, that's true! 🤦 Really nice catch! But I think the correct fix for the issue is to pull the channel read out of the conditional so that it's always evaluated, like so:
> 
> ```go
> 	for p := 0; p < partitions; p++ {
> 		next := <-results
> 		found = found || next
> 	}
> ```
> 
> That way it just fixes the mismatch between how it was intended to work and how it was implemented without introducing additional synchronization. WDYT?

The problem with that is all goroutines need to complete a full pass, so you're not achieving the stated goal and it evaluates predicate for every value in the worst case scenario even if the very first call is successful.
```go
// A partition will terminate upon the first encountered value for which the
// predicate returns true, and as such, the predicate may not be called for
// every value.
```

**Comment by stevenh** [comment]
I just spotted the benchmarks aren't working as expected and are really just testing the setup code, moving it out even with the sync there is still a significant benefit to the parallelisation.

The performance varies based on the location of result but that's expected.
```shell
go test -run=x -bench=Any -benchtime=10s
goos: linux
goarch: amd64
pkg: github.com/jussi-kalliokoski/par
cpu: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
BenchmarkAny/serial-8                196          59547531 ns/op
BenchmarkAny/parallel-8              963          12631547 ns/op
PASS
ok      github.com/jussi-kalliokoski/par        34.135s
```

**Comment by jussi-kalliokoski** [comment]
> I just spotted the benchmarks aren't working as expected and are really just testing the setup code, moving it out even with the sync there is still a significant benefit to the parallelisation.

Yup! Sorry, I didn't notice you also fixed them, so I made #3 to improve them to get more representative results.

> The problem with that is all goroutines need to complete a full pass, so you're not achieving the stated goal and it evaluates predicate for every value in the worst case scenario even if the very first call is successful.

Yeah, my assumption about the synchronization overhead being more significant than early exits was based on the previous (flawed) benchmarks, and with the fixed benchmarks, you're correct that my assumption was incorrect. In fact, this implementation is faster in the worst, average and best case scenarios. :+1:

**Review by jussi-kalliokoski — APPROVED** [review]

**Pull request merged**
